apiVersion: v1
kind: Service
metadata:
  name: frontendreverseproxy-easytrade-external
  annotations:
    cloud.google.com/l4-rbs: "enabled"
spec:
  type: LoadBalancer
  selector:
    app: frontendreverseproxy
  ports:
    - name: http
      port: 80
      targetPort: 80