apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: easytrade-ephemerals
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        owner: ArctiqDynatraceDemo
        repo: easytrade
        tokenRef:
            secretName: github-token
            key: token
      requeueAfterSeconds: 60
  template:
    metadata:
      name: "easytrade-preview-pr-{{.number}}"
      labels:
        image: "credit-card-order-service"
        tag: "pr.{{.number}}-sha.{{.head_short_sha}}"
        preview: "true"
      annotations:
        kargo.akuity.io/authorized-stage: "easytrade:pr-{{.number}}-preview"
        preview.argoproj.io/code-repo-url: "https://github.com/arctiqdynatracedemo/easytrade.git"
        preview.argoproj.io/code-revision: "{{.head_sha}}"
        notifications.argoproj.io/subscribe.on-preview-validation-succeeded.github: ""
        notifications.argoproj.io/subscribe.on-preview-validation-failed.github: ""
        notifications.argoproj.io/subscribe.on-preview-validation-running.github: ""
    spec:
      project: "default"
      source:
        repoURL: https://github.com/ArctiqDynatraceDemo/gitops
        targetRevision: HEAD
        path: easytrade/previews
        kustomize:
          namePrefix: "pr-{{.number}}-"
          patches:
          - target:
              kind: Warehouse
              name: easytrade-credit-card
            patch: |-
              - op: add
                path: /spec/subscriptions/0/image/allowTagsRegexes/-
                value: "^pr.{{.number}}-"
          images:
            - "ghcr.io/arctiqdynatracedemo/easytrade/credit-card-order-service:pr.{{.number}}-sha.{{.head_short_sha}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: 'easytrade-preview-pr-{{.number}}'
      syncPolicy:
        automated:
          enabled: true
      
      
