apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: easytrade-ephemerals
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        owner: ArctiqDynatraceDemo
        repo: easytrade
        tokenRef:
            secretName: github-token
            key: token
        labels:
        - preview
      requeueAfterSeconds: 60
  template:
    metadata:
      name: "easytrade-preview-pr-{{.number}}"
      labels:
        preview: "true"
      annotations:
        preview.argoproj.io/code-repo-url: "https://github.com/arctiqdynatracedemo/easytrade.git"
        notifications.argoproj.io/subscribe.on-preview-validation-succeeded.github: ""
        notifications.argoproj.io/subscribe.on-preview-validation-failed.github: ""
        notifications.argoproj.io/subscribe.on-preview-validation-running.github: ""
    spec:
      project: "default"
      source:
        repoURL: https://github.com/ArctiqDynatraceDemo/gitops
        targetRevision: HEAD
        path: easytrade/previews
        kustomize:
          images:
            - "ghcr.io/arctiqdynatracedemo/easytrade/accountservice:pr.{{.number}}-sha.{{.head_short_sha}}"
            - "ghcr.io/arctiqdynatracedemo/easytrade/aggregator-service:pr.{{.number}}-sha.{{.head_short_sha}}"
            - "ghcr.io/arctiqdynatracedemo/easytrade/broker-service:pr.{{.number}}-sha.{{.head_short_sha}}"
            - "ghcr.io/arctiqdynatracedemo/easytrade/calculationservice:pr.{{.number}}-sha.{{.head_short_sha}}"
            - "ghcr.io/arctiqdynatracedemo/easytrade/credit-card-order-service:pr.{{.number}}-sha.{{.head_short_sha}}"
            - "ghcr.io/arctiqdynatracedemo/easytrade/db:pr.{{.number}}-sha.{{.head_short_sha}}"
            - "ghcr.io/arctiqdynatracedemo/easytrade/engine:pr.{{.number}}-sha.{{.head_short_sha}}"
            - "ghcr.io/arctiqdynatracedemo/easytrade/feature-flag-service:pr.{{.number}}-sha.{{.head_short_sha}}"
            - "ghcr.io/arctiqdynatracedemo/easytrade/frontend:pr.{{.number}}-sha.{{.head_short_sha}}"
            - "ghcr.io/arctiqdynatracedemo/easytrade/frontendreverseproxy:pr.{{.number}}-sha.{{.head_short_sha}}"
            - "ghcr.io/arctiqdynatracedemo/easytrade/loadgen:pr.{{.number}}-sha.{{.head_short_sha}}"
            - "ghcr.io/arctiqdynatracedemo/easytrade/loginservice:pr.{{.number}}-sha.{{.head_short_sha}}"
            - "ghcr.io/arctiqdynatracedemo/easytrade/manager:pr.{{.number}}-sha.{{.head_short_sha}}"
            - "ghcr.io/arctiqdynatracedemo/easytrade/offerservice:pr.{{.number}}-sha.{{.head_short_sha}}"
            - "ghcr.io/arctiqdynatracedemo/easytrade/pricing-service:pr.{{.number}}-sha.{{.head_short_sha}}"
            - "ghcr.io/arctiqdynatracedemo/easytrade/problem-operator:pr.{{.number}}-sha.{{.head_short_sha}}"
            - "ghcr.io/arctiqdynatracedemo/easytrade/rabbitmq:pr.{{.number}}-sha.{{.head_short_sha}}"
            - "ghcr.io/arctiqdynatracedemo/easytrade/third-party-service:pr.{{.number}}-sha.{{.head_short_sha}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: 'easytrade-preview-pr-{{.number}}'
      syncPolicy:
        automated:
          enabled: true
      
      
