apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: easytrade
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: easytrade
  namespace: easytrade
spec:
  promotionPolicies:
  - stageSelector:
      name: dev
    autoPromotionEnabled: true
  - stageSelector:
      name: qa
    autoPromotionEnabled: true
  - stageSelector:
      name: uat
    autoPromotionEnabled: true