apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  # GitHub notifier (uses a GitHub App)
  service.github: |
    appID: 2861001
    installationID: 109994388
    privateKey: $github-privateKey

  # Optional but recommended so targetURL can link back to Argo CD UI
  context: |
    argocdUrl: http://localhost:8080

  # Template: set commit status on *code repo*, not the config repo
  template.preview-validation-status: |
    message: |
      Preview validation for {{.app.metadata.name}}: {{.app.status.operationState.phase}}
    github:
      repoURLPath: '{{ index .app.metadata.annotations "preview.argoproj.io/code-repo-url" }}'
      revisionPath: '{{ index .app.metadata.annotations "preview.argoproj.io/code-revision" }}'
      status:
        label: "preview/validation"
        targetURL: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
        state: >
          {{- if eq .app.status.operationState.phase "Succeeded" -}}success
          {{- else if eq .app.status.operationState.phase "Failed" -}}failure
          {{- else if eq .app.status.operationState.phase "Error" -}}error
          {{- else -}}pending{{- end -}}
      pullRequestComment:
        content: |
          Application {{.app.metadata.name}} is now running new version of deployments manifests.
          See more here: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true
        commentTag: "continuous-delivery/{{.app.metadata.name}}"
      checkRun:
        name: "continuous-delivery/{{.app.metadata.name}}"
        details_url: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
        status: completed
        conclusion: success
        started_at: "YYYY-MM-DDTHH:MM:SSZ"
        completed_at: "YYYY-MM-DDTHH:MM:SSZ"
        output:
          title: "Deployment of {{.app.metadata.name}} on ArgoCD"
          summary: "Application {{.app.metadata.name}} is now running new version of deployments manifests."
          text: |
            Application {{.app.metadata.name}} is now running new version of deployments manifests.
            See more here: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true

  # Triggers
  trigger.on-preview-validation-succeeded: |
    - when: app.metadata.labels["preview"] == "true" && app.status?.operationState.phase in ['Succeeded'] && time.Now().Sub(time.Parse(app.status?.operationState.finishedAt)).Minutes() <= 5
      send: [preview-validation-status]
      oncePer: app.metadata.annotations["preview.argoproj.io/code-revision"]

  trigger.on-preview-validation-failed: |
    - when: app.metadata.labels["preview"] == "true" && app.status?.operationState.phase in ['Failed','Error']
      send: [preview-validation-status]
      oncePer: app.metadata.annotations["preview.argoproj.io/code-revision"]

  trigger.on-preview-validation-running: |
    - when: app.metadata.labels["preview"] == "true" && app.status?.operationState.phase in ['Running']
      send: [preview-validation-status]
      oncePer: app.metadata.annotations["preview.argoproj.io/code-revision"]