apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  # GitHub notifier (uses a GitHub App)
  service.github: |
    appID: 2861001
    installationID: 109994388
    privateKey: $github-privateKey

  # Optional but recommended so targetURL can link back to Argo CD UI
  context: |
    argocdUrl: http://localhost:8080

  # Template: set commit status on *code repo*, not the config repo
  template.preview-validation-status: |
    message: |
      Preview validation for {{.app.metadata.name}}: {{.app.status.operationState.phase}}
    github:
      repoURLPath: '{{ index .app.metadata.annotations "preview.argoproj.io/code-repo-url" }}'
      revisionPath: >
        {{- range .app.status.summary.images }}
          {{- if (hasPrefix . "ghcr.io/arctiqdynatracedemo/easytrade") }}
            {{- index (splitList ":" .) 1 -}}
            {{break}}
          {{- end }}
        {{- end }}
      status:
        label: "preview/validation"
        targetURL: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
        state: >
          {{- if eq .app.status.operationState.phase "Succeeded" -}}success
          {{- else if eq .app.status.operationState.phase "Failed" -}}failure
          {{- else if eq .app.status.operationState.phase "Error" -}}error
          {{- else -}}pending{{- end -}}
      pullRequestComment:
          commentTag: "continuous-delivery/{{.app.metadata.name}}"
          content: |
            {{- if eq .app.status.operationState.phase "Succeeded" -}}
            :green_circle: Application **{{.app.metadata.name}}** has been successfully *synced* at {{.app.status.operationState.startedAt}}.
            {{- else if eq .app.status.operationState.phase "Failed" -}}
            :red_circle: Application **{{.app.metadata.name}}** sync has failed at {{.app.status.operationState.startedAt}}.
            {{- else if eq .app.status.operationState.phase "Error" -}}
            :red_circle: Application **{{.app.metadata.name}}** sync encountered an error at {{.app.status.operationState.startedAt}}.
            {{- else if eq .app.status.operationState.phase "Running" -}}
            :yellow_circle: Application **{{.app.metadata.name}}** sync and validation started at {{.app.status.operationState.startedAt}}.
            {{- end -}}
            {{- if .app.status.summary.externalURLs }}
              {{- range .app.status.summary.externalURLs }}
            :arrow_right: :globe_with_meridians: {{ . }}
              {{- end }}
            {{- else }}
            :warning: :globe_with_meridians: No external URLs found.
            {{- end }}
            :worm: See the details in [ArgoCD]({{.context.argocdUrl}}/applications/{{.app.metadata.name}}).
      checkRun:
        name: "continuous-delivery/{{.app.metadata.name}}"
        details_url: "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true"
        status: completed
        conclusion: success
        started_at: "YYYY-MM-DDTHH:MM:SSZ"
        completed_at: "YYYY-MM-DDTHH:MM:SSZ"
        output:
          title: "Deployment of {{.app.metadata.name}} on ArgoCD"
          summary: "Application {{.app.metadata.name}} is now running new version of deployments manifests."
          text: |
            Application {{.app.metadata.name}} is now running new version of deployments manifests.
            See more here: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true

  # Triggers
  trigger.on-preview-validation-succeeded: |
    - when: app.metadata.labels["preview"] == "true" && app.status?.operationState.phase in ['Succeeded'] && time.Now().Sub(time.Parse(app.status?.operationState.finishedAt)).Minutes() <= 5 && time.Now().Sub(time.Parse(app.status?.operationState.finishedAt)).Minutes() >= 1
      send: [preview-validation-status]

  trigger.on-preview-validation-failed: |
    - when: app.metadata.labels["preview"] == "true" && app.status?.operationState.phase in ['Failed','Error']
      send: [preview-validation-status]

  trigger.on-preview-validation-running: |
    - when: app.metadata.labels["preview"] == "true" && app.status?.operationState.phase in ['Running']
      send: [preview-validation-status]
