apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: preview-wait-60s
spec:
  metrics:
  - name: wait-60-seconds
    successCondition: status.succeeded > 0
    failureLimit: 1
    provider:
      job:
        spec:
          backoffLimit: 0
          template:
            spec:
              restartPolicy: Never
              containers:
              - name: wait
                image: busybox:1.36
                command:
                - sh
                - -c
                - |
                  echo "Starting 60s validation..."
                  sleep 60
                  echo "Validation complete."
                  exit 0
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisRun
metadata:
  name: easytrade-analysis
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded,HookFailed
spec:
  metrics:
  - name: wait-60-seconds
    successCondition: status.succeeded > 0
    failureLimit: 1
    provider:
      job:
        spec:
          backoffLimit: 0
          template:
            spec:
              restartPolicy: Never
              containers:
              - name: wait
                image: busybox:1.36
                command:
                - sh
                - -c
                - |
                  echo "Starting 60s validation..."
                  sleep 60
                  echo "Validation complete."
                  exit 0