apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: preview
  namespace: easytrade
spec:
  promotionTemplate:
    spec:
      steps:
      - as: ""
        config:
          apps:
          - selector:
              matchLabels:
                image: ${{ last(split(imageFrom('ghcr.io/arctiqdynatracedemo/easytrade/credit-card-order-service').RepoURL, "/"))  }}
                tag: ${{ imageFrom('ghcr.io/arctiqdynatracedemo/easytrade/credit-card-order-service').Tag }}
            sources:
            - repoURL: https://github.com/ArctiqDynatraceDemo/gitops
              kustomize:
                images:
                - repoURL: ghcr.io/arctiqdynatracedemo/easytrade/credit-card-order-service
                  tag: ${{ imageFrom('ghcr.io/arctiqdynatracedemo/easytrade/credit-card-order-service').Tag }}
        continueOnError: false
        if: ""
        uses: argocd-update
  requestedFreight:
  - origin:
      kind: Warehouse
      name: easytrade-credit-card
    sources:
      autoPromotionOptions:
        selectionPolicy: NewestFreight
      direct: true
      stages: []
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: easytrade-credit-card
  namespace: easytrade
spec:
  freightCreationPolicy: Automatic
  interval: 1m0s
  subscriptions:
  - image:
      allowTagsRegexes: []
      cacheByTag: false
      discoveryLimit: 20
      imageSelectionStrategy: NewestBuild
      repoURL: ghcr.io/arctiqdynatracedemo/easytrade/credit-card-order-service
      strictSemvers: true