apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: credit-card-order-service
spec:
  replicas: 1

  # Label selector for pods. Existing ReplicaSets whose pods are selected by
  # this will be the ones affected by this rollout. It must match the pod
  # template's labels.
  selector:
    matchLabels:
      app: credit-card-order-service

  # Template describes the pods that will be created. Same as deployment.
  # If used, then do not use Rollout workloadRef property.
  template:
    metadata:
      labels:
        app: credit-card-order-service
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
        - name: credit-card-order-service
          image: ghcr.io/arctiqdynatracedemo/easytrade/credit-card-order-service:fa6ccf2
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: feature-flag-service-setup
          env:
            - name: PROXY_PREFIX
              value: "credit-card-order-service"
            - name: THIRD_PARTY_SERVICE_HOSTANDPORT
              value: "third-party-service:8080"
            - name: WORK_DELAY
              value: "300"
            - name: WORK_RATE
              value: "900"
            - name: MSSQL_CONNECTIONSTRING
              valueFrom:
                configMapKeyRef:
                  name: connection-strings
                  key: JAVA_CONNECTION_STRING
          resources:
            requests:
              cpu: 20m
              memory: 650Mi
            limits:
              memory: 650Mi

  # Minimum number of seconds for which a newly created pod should be ready
  # without any of its container crashing, for it to be considered available.
  # Defaults to 0 (pod will be considered available as soon as it is ready)
  minReadySeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: credit-card-order-service
spec:
  type: ClusterIP
  selector:
    app: credit-card-order-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
